name: Build Debug APK

on:
  push:
    branches: [ "**" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Assemble debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: mpv-android-anime4k-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 7
